name: json2dart
description: Gernerating Dart model class from Json file.
version: 0.0.1
author: wenliang.xu@gmail.com
homepage: https://github.com/xwl7001/json2dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  dart_style: ^1.2.9
  path: ^1.6.2
  args: ^1.5.2
  build: ^1.1.6
  glob: ^1.1.7
  logging: ^0.11.3+2
  io: ^0.3.3
  build_resolvers: ^1.0.6
  build_runner_core: ^3.0.6
  build_runner: ^1.6.1
  json_annotation: ^3.0.0
  json_serializable: ^3.0.0
  mustache: ^1.1.1

dev_dependencies:
  test: ^1.5.1
