name: json2dart
description: Gernerating Dart model class from Json file.
version: 0.0.1
author: wenliang.xu@gmail.com
homepage: https://github.com/xwl7001/json2dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  convert: ^3.0.0
  dart_style: ^1.3.6
  path: ^1.6.2
  args: ^2.0.0
  # build: ^1.3.0
  glob: ^2.0.0
  # logging: ^0.11.3+2
  io: ^0.3.3
  # build_resolvers: ^1.3.11
  # build_runner_core: ^6.0.1
  # build_runner: ^1.10.2
  json_annotation: ^3.0.0
  json_serializable: ^3.0.0
  mustache: ^1.1.1

dev_dependencies:
  test: any # ^1.5.1
